/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Vistas;

import Clases.ClsCandidato;
import Clases.ClsEleccion;
import Clases.ClsMensaje;
import Clases.ClsVotante;
import Controladores.CtlCandidato;
import Controladores.CtlEleccion;
import Controladores.CtlVotante;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FrameVotar extends javax.swing.JFrame {
    
    
    CtlEleccion controladorEleccion;   
    LinkedList<ClsEleccion> elecciones;
    

    CtlVotante controladorVotante;
    CtlCandidato controlador;
    FrameGestorCandidato votacion = new FrameGestorCandidato();
    
    
    public FrameVotar() {
        initComponents();
        this.controladorVotante = new CtlVotante();
        this.controlador = new CtlCandidato();
        this.obtenerAnios();        
        
        this.controladorEleccion = new CtlEleccion();
    
    }
    public void obtenerAnios(){
        
        LinkedList<String> anios = this.controladorVotante.ObtenerAnios();
        DefaultComboBoxModel model = (DefaultComboBoxModel) this.comboAnio.getModel();
        model.removeAllElements();

        for (String anio : anios) {
            model.addElement(anio);
        }

        this.comboAnio.setModel(model);

    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoComprobarCedula = new javax.swing.JTextField();
        botonVotar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVotosElecciones = new javax.swing.JTable();
        botonComprobarCedula = new javax.swing.JButton();
        botonVolverV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboAnio = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoComprobarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoComprobarCedulaActionPerformed(evt);
            }
        });

        botonVotar.setText("Votar");
        botonVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVotarActionPerformed(evt);
            }
        });

        tablaVotosElecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Candidato", "Partido"
            }
        ));
        tablaVotosElecciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVotosEleccionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVotosElecciones);

        botonComprobarCedula.setText("Comprobar Cedula");
        botonComprobarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprobarCedulaActionPerformed(evt);
            }
        });

        botonVolverV.setText("Volver");
        botonVolverV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverVActionPerformed(evt);
            }
        });

        jLabel1.setText("CARTILLA DE VOTACIÓN");

        jLabel2.setText("Ingrese su cédula");

        comboAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAnioActionPerformed(evt);
            }
        });

        jLabel3.setText("Elija año de elecciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(botonVolverV))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonVotar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoComprobarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botonComprobarCedula))
                                    .addComponent(jLabel2))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(botonVolverV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoComprobarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonComprobarCedula))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonVotar)
                        .addGap(83, 83, 83))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVotarActionPerformed
        
        int column = 0;
        int row = this.tablaVotosElecciones.getSelectedRow();
        String candidato = this.tablaVotosElecciones.getModel().getValueAt(row, column).toString();
        String elecciones = this.comboAnio.getSelectedItem().toString();
        String votante = this.campoComprobarCedula.getText();

        ClsMensaje mensaje = this.controlador.Votos(candidato,elecciones,votante);

        if (mensaje.getTipo().equals(mensaje.OK)) {
            //this.obtenerAnios();
            
            this.dispose();
        }
        
        JOptionPane.showMessageDialog(rootPane, mensaje.getDescripcion());
        
    }//GEN-LAST:event_botonVotarActionPerformed

    private void campoComprobarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoComprobarCedulaActionPerformed
        
    }//GEN-LAST:event_campoComprobarCedulaActionPerformed

    private void botonVolverVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverVActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonVolverVActionPerformed

    private void botonComprobarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprobarCedulaActionPerformed
        
        String numeroDocumento = campoComprobarCedula.getText();
        String anio = this.comboAnio.getSelectedItem().toString();
            
        boolean mensaje = this.controladorVotante.ObtenerCedulaVotante(numeroDocumento);
        boolean mensaje1 = this.controladorVotante.ComprobarVotante(numeroDocumento);
        
        System.out.println(mensaje);
        System.out.println(mensaje1);
        
        if (mensaje & !mensaje1 ) {
           
           this.comboAnio.disable();
           JOptionPane.showMessageDialog(null, "Habilitado para votar");
           DefaultTableModel model = (DefaultTableModel) this.tablaVotosElecciones.getModel();
           
           LinkedList<ClsCandidato> lista = this.controladorEleccion.ObtenerCandidatosEleccion(anio);
                

            model.setRowCount(0);

            for (ClsCandidato candidato : lista) {

            Object[] row = {candidato.getNumeroDocumento(), candidato.getNombre(), candidato.getPartidoPolitico()};
            model.addRow(row);
        }
            
            }else{
           JOptionPane.showMessageDialog(null, "No esta habilitado para votar");
            }
        
        
            
           // int column = 0;
            //int row = 
           
           

           
            
        
        
    }//GEN-LAST:event_botonComprobarCedulaActionPerformed

    private void tablaVotosEleccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVotosEleccionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaVotosEleccionesMouseClicked

    private void comboAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAnioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameVotar().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComprobarCedula;
    private javax.swing.JButton botonVolverV;
    private javax.swing.JButton botonVotar;
    private javax.swing.JTextField campoComprobarCedula;
    private javax.swing.JComboBox<String> comboAnio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVotosElecciones;
    // End of variables declaration//GEN-END:variables

}
